import { PolicyPack } from "@pulumi/policy";
import * as policies from "@bobcatt/pulumi-policies";

/**
 * You may quickly generate the list below using the following command
 *
 * ```
 * find ./aws ./kubernetes -name "*.ts" | grep -v index.ts | while read F; do
 *   N=$(echo "$F" | sed 's/\(.*\/\)\(\w\)\(.*\)\.ts/\1\U\2\E\3/g; s/^\./policies/g; s/\//./g;')
 *   grep "export const" $F | awk '{print $3}' | sed 's/:$/,/' | while read P; do
 *       echo "${N}.${P}"
 *   done
 * done
 * ```
 * ```
 * find ./aws ./kubernetes -name "*.ts" | grep -v index.ts | while read F; do N=$(echo "$F" | sed 's/\(.*\/\)\(\w\)\(.*\)\.ts/\1\U\2\E\3/g; s/^\./policies/g; s/\//./g;'); grep "export const" $F | awk '{print $3}' | sed 's/:$/,/' | while read P; do echo "${N}.${P}";  done; done
 * ```
 */

new PolicyPack("policy-pack-acme-corp-cherry-picking", {
    policies: [
        policies.aws.apigatewayv2.DomainName.enableDomainNameConfiguration,
        policies.aws.apigatewayv2.DomainName.configureDomainNameSecurityPolicy,
        policies.aws.apigatewayv2.Stage.enableAccessLogging,
        policies.aws.apigatewayv2.Stage.configureAccessLogging,
        policies.aws.cloudfront.Distribution.enableAccessLogging,
        policies.aws.cloudfront.Distribution.configureAccessLogging,
        policies.aws.cloudfront.Distribution.configureWaf,
        policies.aws.cloudfront.Distribution.disallowUnencryptedTraffic,
        policies.aws.cloudfront.Distribution.configureSecureTLS,
        policies.aws.cloudfront.Distribution.enableTLSToOrigin,
        policies.aws.cloudfront.Distribution.configureSedureTLSToOrgin,
        policies.aws.ebs.Volume.disallowUnencryptedVolume,
        policies.aws.ebs.Volume.configureCustomerManagedKey,
        policies.aws.ec2.Instance.disallowPublicIP,
        policies.aws.ec2.Instance.disallowUnencryptedRootBlockDevice,
        policies.aws.ec2.Instance.disallowUnencryptedBlockDevice,
        policies.aws.ec2.LaunchConfiguration.disallowPublicIP,
        policies.aws.ec2.LaunchConfiguration.disallowUnencryptedRootBlockDevice,
        policies.aws.ec2.LaunchConfiguration.disallowUnencryptedBlockDevice,
        policies.aws.ec2.LaunchTemplate.disallowPublicIP,
        policies.aws.ec2.LaunchTemplate.disallowUnencryptedBlockDevice,
        policies.aws.ec2.SecurityGroup.missingDescription,
        policies.aws.ec2.SecurityGroup.disallowInboundHttpTraffic,
        policies.aws.ec2.SecurityGroup.disallowPublicInternetIngress,
        policies.aws.ecr.Repository.configureImageScan,
        policies.aws.ecr.Repository.enableImageScan,
        policies.aws.ecr.Repository.disallowMutableImage,
        policies.aws.ecr.Repository.disallowUnencryptedRepository,
        policies.aws.ecr.Repository.configureCustomerManagedKey,
        policies.aws.efs.FileSystem.disallowUnencryptedFileSystem,
        policies.aws.efs.FileSystem.configureCustomerManagedKey,
        policies.aws.efs.FileSystem.disallowSingleAvailabilityZone,
        policies.aws.eks.Cluster.enableClusterEncryptionConfig,
        policies.aws.eks.Cluster.disallowAPIEndpointPublicAccess,
        policies.aws.elb.LoadBalancer.disallowInboundHttpTraffic,
        policies.aws.elb.LoadBalancer.configureMultiAvailabilityZone,
        policies.aws.elb.LoadBalancer.configureAccessLogging,
        policies.aws.elb.LoadBalancer.enableHealthCheck,
        policies.aws.kms.Key.enableKeyRotation,
        policies.aws.kms.Key.missingDescription,
        policies.aws.kms.Key.disallowBypassPolicyLockoutSafetyCheck,
        policies.aws.lambda.Function.enableTracingConfig,
        policies.aws.lambda.Function.configureTracingConfig,
        policies.aws.lambda.Permission.configureSourceArn,
        policies.awsnative.cloudfront.Distribution.enableAccessLogging,
        policies.awsnative.cloudfront.Distribution.configureAccessLogging,
        policies.awsnative.cloudfront.Distribution.configureWaf,
        policies.awsnative.cloudfront.Distribution.disallowUnencryptedTraffic,
        policies.awsnative.cloudfront.Distribution.configureSecureTLS,
        policies.awsnative.cloudfront.Distribution.enableTLSToOrigin,
        policies.awsnative.cloudfront.Distribution.configureSedureTLSToOrgin,
        policies.awsnative.ec2.Volume.disallowUnencryptedVolume,
        policies.awsnative.ec2.Volume.configureCustomerManagedKey,
        policies.awsnative.ecr.Repository.configureImageScan,
        policies.awsnative.ecr.Repository.enableImageScan,
        policies.awsnative.ecr.Repository.disallowMutableImage,
        policies.awsnative.ecr.Repository.disallowUnencryptedRepository,
        policies.awsnative.ecr.Repository.configureCustomerManagedKey,
        policies.awsnative.efs.FileSystem.disallowUnencryptedFileSystem,
        policies.awsnative.efs.FileSystem.configureCustomerManagedKey,
        policies.awsnative.efs.FileSystem.disallowSingleAvailabilityZone,
        policies.awsnative.efs.FileSystem.disallowBypassPolicyLockoutSafetyCheck,
        policies.awsnative.eks.Cluster.enableClusterEncryptionConfig,
        policies.awsnative.eks.Cluster.disallowAPIEndpointPublicAccess,
        policies.awsnative.kms.Key.enableKeyRotation,
        policies.awsnative.kms.Key.missingDescription,
        policies.awsnative.lambda.Function.enableTracingConfig,
        policies.awsnative.lambda.Function.configureTracingConfig,
        policies.awsnative.rds.DbCluster.enableBackupRetention,
        policies.awsnative.rds.DbCluster.configureBackupRetention,
        policies.awsnative.rds.DbCluster.disallowUnencryptedStorage,
        policies.awsnative.rds.DbCluster.configureCustomerManagedKey,
        policies.awsnative.rds.DbInstance.enableBackupRetention,
        policies.awsnative.rds.DbInstance.configureBackupRetention,
        policies.awsnative.rds.DbInstance.enablePerformanceInsights,
        policies.awsnative.rds.DbInstance.disallowUnencryptedPerformanceInsights,
        policies.awsnative.rds.DbInstance.disallowPublicAccess,
        policies.awsnative.rds.DbInstance.disallowUnencryptedStorage,
        policies.awsnative.rds.DbInstance.configureCustomerManagedKey,
        policies.awsnative.s3.Bucket.disallowPublicRead,
        policies.awsnative.s3.Bucket.enableReplicationConfiguration,
        policies.awsnative.s3.Bucket.configureReplicationConfiguration,
        policies.awsnative.s3.Bucket.enableServerSideEncryption,
        policies.awsnative.s3.Bucket.configureServerSideEncryptionKMS,
        policies.awsnative.s3.Bucket.configureServerSideEncryptionCustomerManagedKey,
        policies.awsnative.s3.Bucket.enableServerSideEncryptionBucketKey,
        policies.aws.rds.ClusterInstance.enablePerformanceInsights,
        policies.aws.rds.ClusterInstance.disallowUnencryptedPerformanceInsights,
        policies.aws.rds.ClusterInstance.disallowPublicAccess,
        policies.aws.rds.Cluster.enableBackupRetention,
        policies.aws.rds.Cluster.configureBackupRetention,
        policies.aws.rds.Cluster.disallowUnencryptedStorage,
        policies.aws.rds.Cluster.configureCustomerManagedKey,
        policies.aws.rds.Instance.enableBackupRetention,
        policies.aws.rds.Instance.configureBackupRetention,
        policies.aws.rds.Instance.disallowClassicResources,
        policies.aws.rds.Instance.enablePerformanceInsights,
        policies.aws.rds.Instance.disallowUnencryptedPerformanceInsights,
        policies.aws.rds.Instance.disallowPublicAccess,
        policies.aws.rds.Instance.disallowUnencryptedStorage,
        policies.aws.rds.Instance.configureCustomerManagedKey,
        policies.aws.s3.Bucket.disallowPublicRead,
        policies.aws.s3.Bucket.enableReplicationConfiguration,
        policies.aws.s3.Bucket.configureReplicationConfiguration,
        policies.aws.s3.Bucket.enableServerSideEncryption,
        policies.aws.s3.Bucket.configureServerSideEncryptionKMS,
        policies.aws.s3.Bucket.configureServerSideEncryptionCustomerManagedKey,
        policies.aws.s3.Bucket.enableServerSideEncryptionBucketKey,
        policies.aws.secretsmanager.Secret.missingDescription,
        policies.aws.secretsmanager.Secret.configureCustomerManagedKey,
        policies.kubernetes.apps.v1.Deployment.configureMinimumReplicaCount,
        policies.kubernetes.apps.v1.Deployment.configureRecommendedLabel,
        policies.kubernetes.apps.v1.ReplicaSet.configureMinimumReplicaCount,
        policies.kubernetes.apps.v1.ReplicaSet.configureRecommendedLabel,
        policies.kubernetes.core.v1.Pod.disallowPod,
        policies.kubernetes.core.v1.Service.configureRecommendedLabel,
    ],
});
