import { PolicyPack } from "@pulumi/policy";
import * as awsPolicies from "@pulumi-premium-policies/aws-policies";
import * as azurePolicies from "@pulumi-premium-policies/azure-policies";
import * as k8sPolicies from "@pulumi-premium-policies/kubernetes-policies";

/**
 * You may quickly generate the list below using the following command
 *
 * ```
 * find ./aws ./kubernetes -name "*.ts" | grep -v index.ts | while read F; do
 *   N=$(echo "$F" | sed 's/\(.*\/\)\(\w\)\(.*\)\.ts/\1\U\2\E\3/g; s/^\./policies/g; s/\//./g;')
 *   grep "export const" $F | awk '{print $3}' | sed 's/:$/,/' | while read P; do
 *       echo "${N}.${P}"
 *   done
 * done
 * ```
 * ```
 * find ./aws ./kubernetes -name "*.ts" | grep -v index.ts | while read F; do N=$(echo "$F" | sed 's/\(.*\/\)\(\w\)\(.*\)\.ts/\1\U\2\E\3/g; s/^\./policies/g; s/\//./g;'); grep "export const" $F | awk '{print $3}' | sed 's/:$/,/' | while read P; do echo "${N}.${P}";  done; done
 * ```
 */

new PolicyPack("policy-pack-acme-corp-cherry-picking", {
    policies: [
        awsPolicies.aws.lambda.Function.missingDescription,
        awsPolicies.aws.lambda.Function.enableTracingConfig,
        awsPolicies.aws.lambda.Function.configureTracingConfig,
        awsPolicies.aws.lambda.Permission.configureSourceArn,
        awsPolicies.aws.ec2.SecurityGroup.missingDescription,
        awsPolicies.aws.ec2.SecurityGroup.missingIngressRuleDescription,
        awsPolicies.aws.ec2.SecurityGroup.missingEgressRuleDescription,
        awsPolicies.aws.ec2.SecurityGroup.disallowInboundHttpTraffic,
        awsPolicies.aws.ec2.SecurityGroup.disallowPublicInternetIngress,
        awsPolicies.aws.ec2.Instance.disallowPublicIp,
        awsPolicies.aws.ec2.Instance.disallowUnencryptedRootBlockDevice,
        awsPolicies.aws.ec2.Instance.disallowUnencryptedBlockDevice,
        awsPolicies.aws.ec2.LaunchTemplate.disallowPublicIp,
        awsPolicies.aws.ec2.LaunchTemplate.disallowUnencryptedBlockDevice,
        awsPolicies.aws.ec2.LaunchTemplate.configureCustomerManagedKey,
        awsPolicies.aws.ec2.LaunchConfiguration.disallowPublicIp,
        awsPolicies.aws.ec2.LaunchConfiguration.disallowUnencryptedRootBlockDevice,
        awsPolicies.aws.ec2.LaunchConfiguration.disallowUnencryptedBlockDevice,
        awsPolicies.aws.athena.Database.missingDescription,
        awsPolicies.aws.athena.Database.disallowUnencryptedDatabase,
        awsPolicies.aws.athena.Database.configureCustomerManagedKey,
        awsPolicies.aws.athena.NamedQuery.missingDescription,
        awsPolicies.aws.athena.Workgroup.missingDescription,
        awsPolicies.aws.athena.Workgroup.disallowUnencryptedWorkgroup,
        awsPolicies.aws.athena.Workgroup.configureCustomerManagedKey,
        awsPolicies.aws.athena.Workgroup.enforceConfiguration,
        awsPolicies.aws.athena.DataCatalog.missingDescription,
        awsPolicies.aws.apigatewayv2.DomainName.enableDomainNameConfiguration,
        awsPolicies.aws.apigatewayv2.DomainName.configureDomainNameSecurityPolicy,
        awsPolicies.aws.apigatewayv2.Stage.enableAccessLogging,
        awsPolicies.aws.apigatewayv2.Stage.configureAccessLogging,
        awsPolicies.aws.elb.LoadBalancer.disallowUnencryptedTraffic,
        awsPolicies.aws.elb.LoadBalancer.configureMultiAvailabilityZone,
        awsPolicies.aws.elb.LoadBalancer.configureAccessLogging,
        awsPolicies.aws.elb.LoadBalancer.enableHealthCheck,
        awsPolicies.aws.alb.LoadBalancer.enableAccessLogging,
        awsPolicies.aws.alb.LoadBalancer.configureAccessLogging,
        awsPolicies.aws.alb.Listener.disallowUnencryptedTraffic,
        awsPolicies.aws.alb.Listener.configureSecureTls,
        awsPolicies.aws.ebs.Volume.disallowUnencryptedVolume,
        awsPolicies.aws.ebs.Volume.configureCustomerManagedKey,
        awsPolicies.aws.cloudfront.Distribution.enableAccessLogging,
        awsPolicies.aws.cloudfront.Distribution.configureAccessLogging,
        awsPolicies.aws.cloudfront.Distribution.configureWaf,
        awsPolicies.aws.cloudfront.Distribution.disallowUnencryptedTraffic,
        awsPolicies.aws.cloudfront.Distribution.configureSecureTls,
        awsPolicies.aws.cloudfront.Distribution.enableTlsToOrigin,
        awsPolicies.aws.cloudfront.Distribution.configureSecureTlsToOrigin,
        awsPolicies.aws.secretsmanager.Secret.missingDescription,
        awsPolicies.aws.secretsmanager.Secret.configureCustomerManagedKey,
        awsPolicies.aws.rds.Instance.enableBackupRetention,
        awsPolicies.aws.rds.Instance.configureBackupRetention,
        awsPolicies.aws.rds.Instance.disallowClassicResource,
        awsPolicies.aws.rds.Instance.enablePerformanceInsights,
        awsPolicies.aws.rds.Instance.disallowUnencryptedPerformanceInsights,
        awsPolicies.aws.rds.Instance.disallowPublicAccess,
        awsPolicies.aws.rds.Instance.disallowUnencryptedStorage,
        awsPolicies.aws.rds.Instance.configureCustomerManagedKey,
        awsPolicies.aws.rds.ClusterInstance.enablePerformanceInsights,
        awsPolicies.aws.rds.ClusterInstance.disallowUnencryptedPerformanceInsights,
        awsPolicies.aws.rds.ClusterInstance.disallowPublicAccess,
        awsPolicies.aws.rds.Cluster.enableBackupRetention,
        awsPolicies.aws.rds.Cluster.configureBackupRetention,
        awsPolicies.aws.rds.Cluster.disallowUnencryptedStorage,
        awsPolicies.aws.rds.Cluster.configureCustomerManagedKey,
        awsPolicies.aws.rds.Cluster.disallowSingleAvailabilityZone,
        awsPolicies.aws.kms.Key.enableKeyRotation,
        awsPolicies.aws.kms.Key.missingDescription,
        awsPolicies.aws.kms.Key.disallowBypassPolicyLockoutSafetyCheck,
        awsPolicies.aws.appflow.Flow.configureCustomerManagedKey,
        awsPolicies.aws.appflow.Flow.missingDescription,
        awsPolicies.aws.appflow.ConnectorProfile.configureCustomerManagedKey,
        awsPolicies.aws.s3.Bucket.disallowPublicRead,
        awsPolicies.aws.s3.Bucket.enableReplicationConfiguration,
        awsPolicies.aws.s3.Bucket.configureReplicationConfiguration,
        awsPolicies.aws.s3.Bucket.enableServerSideEncryption,
        awsPolicies.aws.s3.Bucket.configureServerSideEncryptionKms,
        awsPolicies.aws.s3.Bucket.configureServerSideEncryptionCustomerManagedKey,
        awsPolicies.aws.s3.Bucket.enableServerSideEncryptionBucketKey,
        awsPolicies.aws.ecr.Repository.configureImageScan,
        awsPolicies.aws.ecr.Repository.enableImageScan,
        awsPolicies.aws.ecr.Repository.disallowMutableImage,
        awsPolicies.aws.ecr.Repository.disallowUnencryptedRepository,
        awsPolicies.aws.ecr.Repository.configureCustomerManagedKey,
        awsPolicies.aws.efs.FileSystem.disallowUnencryptedFileSystem,
        awsPolicies.aws.efs.FileSystem.configureCustomerManagedKey,
        awsPolicies.aws.efs.FileSystem.disallowSingleAvailabilityZone,
        awsPolicies.aws.apigateway.DomainName.configureSecurityPolicy,
        awsPolicies.aws.eks.Cluster.enableClusterEncryptionConfig,
        awsPolicies.aws.eks.Cluster.disallowApiEndpointPublicAccess,
        awsPolicies.awsnative.lambda.Function.missingDescription,
        awsPolicies.awsnative.lambda.Function.enableTracingConfig,
        awsPolicies.awsnative.lambda.Function.configureTracingConfig,
        awsPolicies.awsnative.ec2.Volume.disallowUnencryptedVolume,
        awsPolicies.awsnative.ec2.Volume.configureCustomerManagedKey,
        awsPolicies.awsnative.athena.NamedQuery.missingDescription,
        awsPolicies.awsnative.athena.DataCatalog.missingDescription,
        awsPolicies.awsnative.athena.WorkGroup.missingDescription,
        awsPolicies.awsnative.athena.WorkGroup.disallowUnencryptedWorkgroup,
        awsPolicies.awsnative.athena.WorkGroup.configureCustomerManagedKey,
        awsPolicies.awsnative.athena.WorkGroup.enforceConfiguration,
        awsPolicies.awsnative.cloudfront.Distribution.enableAccessLogging,
        awsPolicies.awsnative.cloudfront.Distribution.configureAccessLogging,
        awsPolicies.awsnative.cloudfront.Distribution.configureWafAcl,
        awsPolicies.awsnative.cloudfront.Distribution.disallowUnencryptedTraffic,
        awsPolicies.awsnative.cloudfront.Distribution.configureSecureTls,
        awsPolicies.awsnative.cloudfront.Distribution.enableTlsToOrigin,
        awsPolicies.awsnative.cloudfront.Distribution.configureSecureTlsToOrigin,
        awsPolicies.awsnative.rds.DBCluster.enableBackupRetention,
        awsPolicies.awsnative.rds.DBCluster.configureBackupRetention,
        awsPolicies.awsnative.rds.DBCluster.disallowUnencryptedStorage,
        awsPolicies.awsnative.rds.DBCluster.configureCustomerManagedKey,
        awsPolicies.awsnative.rds.DBCluster.disallowSingleAvailabilityZone,
        awsPolicies.awsnative.rds.DBInstance.enableBackupRetention,
        awsPolicies.awsnative.rds.DBInstance.configureBackupRetention,
        awsPolicies.awsnative.rds.DBInstance.enablePerformanceInsights,
        awsPolicies.awsnative.rds.DBInstance.disallowUnencryptedPerformanceInsights,
        awsPolicies.awsnative.rds.DBInstance.disallowPublicAccess,
        awsPolicies.awsnative.rds.DBInstance.disallowUnencryptedStorage,
        awsPolicies.awsnative.rds.DBInstance.configureCustomerManagedKey,
        awsPolicies.awsnative.kms.Key.enableKeyRotation,
        awsPolicies.awsnative.kms.Key.missingDescription,
        awsPolicies.awsnative.appflow.Flow.configureCustomerManagedKey,
        awsPolicies.awsnative.appflow.Flow.missingDescription,
        awsPolicies.awsnative.appflow.ConnectorProfile.configureCustomerManagedKey,
        awsPolicies.awsnative.s3.Bucket.disallowPublicRead,
        awsPolicies.awsnative.s3.Bucket.enableReplicationConfiguration,
        awsPolicies.awsnative.s3.Bucket.configureReplicationConfiguration,
        awsPolicies.awsnative.s3.Bucket.enableServerSideEncryption,
        awsPolicies.awsnative.s3.Bucket.configureServerSideEncryptionKms,
        awsPolicies.awsnative.s3.Bucket.configureServerSideEncryptionCustomerManagedKey,
        awsPolicies.awsnative.s3.Bucket.enableServerSideEncryptionBucketKey,
        awsPolicies.awsnative.ecr.Repository.configureImageScan,
        awsPolicies.awsnative.ecr.Repository.enableImageScan,
        awsPolicies.awsnative.ecr.Repository.disallowMutableImage,
        awsPolicies.awsnative.ecr.Repository.disallowUnencryptedRepository,
        awsPolicies.awsnative.ecr.Repository.configureCustomerManagedKey,
        awsPolicies.awsnative.efs.FileSystem.disallowUnencryptedFileSystem,
        awsPolicies.awsnative.efs.FileSystem.configureCustomerManagedKey,
        awsPolicies.awsnative.efs.FileSystem.disallowSingleAvailabilityZone,
        awsPolicies.awsnative.efs.FileSystem.disallowBypassPolicyLockoutSafetyCheck,
        awsPolicies.awsnative.apigateway.DomainName.configureSecurityPolicy,
        awsPolicies.awsnative.eks.Cluster.enableClusterEncryptionConfig,
        awsPolicies.awsnative.eks.Cluster.disallowApiEndpointPublicAccess,
        k8sPolicies.kubernetes.apps.v1.ReplicaSet.configureMinimumReplicaCount,
        k8sPolicies.kubernetes.apps.v1.ReplicaSet.configureRecommendedLabels,
        k8sPolicies.kubernetes.apps.v1.ReplicaSet.enableReadOnlyRootFilesystem,
        k8sPolicies.kubernetes.apps.v1.Deployment.configureMinimumReplicaCount,
        k8sPolicies.kubernetes.apps.v1.Deployment.configureRecommendedLabels,
        k8sPolicies.kubernetes.apps.v1.Deployment.enableReadOnlyRootFilesystem,
        k8sPolicies.kubernetes.apps.v1.DaemonSet.configureRecommendedLabels,
        k8sPolicies.kubernetes.apps.v1.DaemonSet.enableReadOnlyRootFilesystem,
        k8sPolicies.kubernetes.apps.v1.StatefulSet.configureRecommendedLabels,
        k8sPolicies.kubernetes.apps.v1.StatefulSet.enableReadOnlyRootFilesystem,
        k8sPolicies.kubernetes.batch.v1.CronJob.configureRecommendedLabels,
        k8sPolicies.kubernetes.batch.v1.CronJob.enableReadOnlyRootFilesystem,
        k8sPolicies.kubernetes.batch.v1.Job.configureRecommendedLabels,
        k8sPolicies.kubernetes.batch.v1.Job.enableReadOnlyRootFilesystem,
        k8sPolicies.kubernetes.policy.v1.PodDisruptionBudget.disallowZeroVoluntaryDisruption,
        k8sPolicies.kubernetes.core.v1.Pod.disallowPod,
        k8sPolicies.kubernetes.core.v1.Service.configureRecommendedLabels,
        k8sPolicies.kubernetes.core.v1.Service.disallowLoadBalancer,
        azurePolicies.azure.compute.LinuxVirtualMachine.disallowPasswordAuthentication,
        azurePolicies.azure.compute.ManagedDisk.disallowUnencryptedManagedDisk,
        azurePolicies.azurenative.compute.VirtualMachine.disallowPasswordAuthentication,
        azurePolicies.azurenative.compute.Disk.disallowUnencryptedDisk,
    ],
});
